### ISSUE TITLE
After changes in unique, .a simple /jtrts.pl fails 

### ISSUE THREAD

**Issue by claudioandre-br** [openwall/john-tests#87]
After changes in unique, TS fails a regular run.

```
form=dynamic_0-raw                guesses: 1500 0:00:00:00 DONE  [PASSED]
Warning: The -mem=20 option is deprecated, use -hash-size=20 (log2 of hash
         table size) and/or -buf=1 (total buffer size, in GB) instead
Error: Requested hash size is unreasonably small (20, 1 M/8 MB)
Execute john (.pot check): ../run/john -ses=tst-  -pot=tst-.pot tst-tst.in --wordlist=tst-pw3 -form=dynamic_0  2>_stderr
.pot CHK:dynamic_0-raw            guesses:    0 -show=   0 N/A N/A : Expected count(s) (1500)  [!!!FAILED6!!!   ret_val=256 exited, return code 1]
```
https://github.com/openwall/john/commit/b2cfb8b3882946d8c5ad6ea99b8b16cddccd87b8

@jfoug, are you available?

**Comment by solardiz** [comment]
FWIW, the smallest memory allocation `unique` now allows is 256 MB with (undocumented) `-buf=0`. When used on tiny inputs, most of this address space is left unwritten, so doesn't use actual memory. Only the hash table is fully initialized, and by default that's 1/8 of total allocation (maybe we should increase that as higher hash table sizes produce between speeds on inputs that actually fill the buffer; the smaller allocation is to account for the case of small input, not to waste time and memor in that case).

**Comment by solardiz** [comment]
I didn't realize TS used that. I don't mind lowering the minimum allowed size back to 20. Should I, @claudioandre-br @jfoug?

**Comment by claudioandre-br** [comment]
TS needs love. But, if we have no perl volunteers, that have to be the solution.

**Comment by solardiz** [comment]
It doesn't really take a _Perl_ volunteer to patch command-line options for an invoked program.

**Comment by magnumripper** [comment]
I can fix this. Actually I have no idea why TS use any options at all for unique.

**Comment by magnumripper** [comment]
f71347a
